    create table equipo (
        descenso boolean,
        numero_victorias integer,
        id bigint not null,
        mejor_jugador varchar(255),
        nombre varchar(255),
        primary key (id)
    )

    create table escuderias (
        id bigint generated by default as identity,
        motor_id bigint unique,
        version bigint,
        color varchar(255),
        nombre varchar(255),
        numero_pilotos varchar(255),
        numero_victorias varchar(255),
        primary key (id)
    )

    create table motores (
        anos_uso integer,
        potencia integer,
        id bigint generated by default as identity,
        version bigint,
        fabricante varchar(255),
        tipo varchar(255),
        primary key (id)
    )

    create table patrocinador (
        años_activos integer not null,
        da_beneficio boolean not null,
        equipo_id bigint unique,
        id bigint not null,
        nombre varchar(255),
        producto varchar(255),
        primary key (id)
    )